[package]
name = "rendezvous-bouncer-irc"
version = "0.3.0"
authors = ["Eunchong Yu <kroisse@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"
publish = false

[dependencies]
failure = "0.1"
irc = "0.13.6"
rendezvous-common = { path = "../common" }
