version: 2.1
executors:
  default:
    machine:
      image: ubuntu-1604:201903-01
    environment:
      CARGO_INCREMENTAL: 0
    working_directory: ~/work
commands:
  install-rust:
    steps:
    - run:
        name: Install Rust
        command: |
          curl -LO https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
          chmod +x rustup-init
          ./rustup-init -y --no-modify-path
          rm rustup-init
          echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
  checkout-and-configure:
    steps:
    - checkout
    - run:
        name: Vendoring dependencies
        command: |
          mkdir -p .cargo && cp deploy/cargo.config .cargo/config
  prepare:
    steps:
    - run:
        name: Install Prerequisites
        command: |
          sudo apt-get -y update
          sudo apt-get -y install cmake curl libssl-dev ninja-build pkg-config zlib1g-dev
    - install-rust
    - checkout-and-configure
    - attach_workspace:
        at: .

jobs:
  vendor:
    executor: default
    steps:
    - install-rust
    - checkout-and-configure
    - restore_cache:
        keys:
        - rendezvous-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Cargo.lock" }}
        - rendezvous-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-
        - rendezvous-{{ .Environment.CIRCLECI_CACHE_VERSION }}-
    - run:
        name: Vendoring dependencies
        command: |
          if [ ! -d vendor ]; then cargo vendor; fi
    - save_cache:
        key: rendezvous-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Cargo.lock" }}
        paths:
        - "vendor"
    - persist_to_workspace:
        root: .
        paths:
        - "vendor"

  test:
    executor: default
    steps:
    - prepare
    - run:
        name: Test
        command: |
          cargo test --all --verbose

  collect-coverage:
    executor: default
    steps:
    - prepare
    - restore_cache:
        keys:
        - rendezvous-tarpaulin-{{ .Environment.CIRCLECI_CACHE_VERSION }}
    - run:
        # https://discuss.circleci.com/t/cargo-tarpaulin-fails/30215/3
        name: Install Tarpaulin
        command: cargo tarpaulin --version || cargo install --force cargo-tarpaulin
        environment:
          RUSTFLAGS: --cfg procmacro2_semver_exempt
    - save_cache:
        key: rendezvous-tarpaulin-{{ .Environment.CIRCLECI_CACHE_VERSION }}
        paths:
        - "~/.cargo/bin/cargo-tarpaulin"
    - run:
        name: Test and collect code coverage
        command: |
          cargo tarpaulin --all --verbose \
            --ignore-tests --forward \
            --exclude-files vendor/**/* \
            --out Xml --ciserver circle-ci
    - run:
        command: ls -lh target/debug/
        when: always
    - run:
        name: Upload Coverage Report
        command: bash <(curl -s https://codecov.io/bash)
    - store_artifacts:
        path: cobertura.xml

workflows:
  version: 2

  test:
    jobs:
    - vendor
    - test:
        requires:
        - vendor
    - collect-coverage:
        requires:
        - test

  weekly:
    triggers:
    - schedule:
        cron: "21 0 * * 5"
        filters:
          branches:
            only:
            - master
    jobs:
    - vendor
    - test:
        requires:
        - vendor
