version: 2

jobs:

  test:
    machine:
      image: ubuntu-1604:201903-01
      environment:
        CARGO_INCREMENTAL: 0
    working_directory: ~/work
    steps:
    - run:
        name: Install Prerequisites
        command: |
          sudo apt-get -y update
          sudo apt-get -y install cmake curl libssl-dev ninja-build pkg-config zlib1g-dev
    - run:
        name: Install Rust
        command: |
          curl -LO https://static.rust-lang.org/rustup/dist/x86_64-unknown-linux-gnu/rustup-init
          chmod +x rustup-init
          ./rustup-init -y --no-modify-path
          rm rustup-init
          echo 'export PATH=$HOME/.cargo/bin:$PATH' >> $BASH_ENV
    - run:
        # https://discuss.circleci.com/t/cargo-tarpaulin-fails/30215/3
        name: Install Tarpaulin
        command: cargo install cargo-tarpaulin
        environment:
          RUSTFLAGS: --cfg procmacro2_semver_exempt
    - checkout
    - restore_cache:
        keys:
        - rendezvous-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Cargo.lock" }}
        - rendezvous-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-
        - rendezvous-{{ .Environment.CIRCLECI_CACHE_VERSION }}-
    - run: cargo build --tests
    - run: cargo test --verbose
    - run:
        name: Collect Coverage Report
        command: |
          cargo tarpaulin --verbose \
            --ignore-tests --forward \
            --out Xml --ciserver circle-ci || echo "Coverage has dismissed"
    - run:
        command: ls -lh target/debug/
        when: always
    - save_cache:
        key: rendezvous-{{ .Environment.CIRCLECI_CACHE_VERSION }}-{{ .Branch }}-{{ checksum "Cargo.lock" }}
        paths:
        - "/usr/local/cargo/registry"
        - "target/debug/deps"
    - run:
        name: Upload Coverage Report
        command: bash <(curl -s https://codecov.io/bash)
    - store_artifacts:
        path: cobertura.xml

workflows:
  version: 2

  test:
    jobs:
    - test

  weekly:
    triggers:
    - schedule:
        cron: "21 0 * * 5"
        filters:
          branches:
            only:
            - master
    jobs:
    - test
