[package]
name = "rendezvous-common"
version = "0.3.0"
authors = ["Eunchong Yu <kroisse@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"
publish = false

[dependencies]
anyhow = "1.0"
nng = "0.5"
parking_lot = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.10"
tracing = "0.1.8"
tracing-subscriber = "0.1.1"
