[package]
name = "rendezvous-server"
version = "0.4.0-dev"
authors = ["Eunchong Yu <kroisse@gmail.com>"]
edition = "2018"
license = "AGPL-3.0"
publish = false

[features]
legacy = ["rendezvous-common/legacy"]

[dependencies]
rendezvous-common = { path = "../common" }
